data_dir: /home/chad/datasets/Mocap2
depth_max: 30
plot_depth: True
tf_bodyInW: [1,0,0,0,0,-1,0,0,0,0,-1,0,0,0,0,1]
tf_camInB: [0,0,1,0,
            1,0,0,0,
            0,1,0,0,
            0,0,0,1]
tf_tagInCam: [0,1,0,0,
              -1,0,0,0,
              0,0,1,0,
              0,0,0,1]
tf_tagFaceInBody: [-1,0,0,0,
                   0, 0,-1,0,
                   0,-1,0,0,
                   0,0,0,1]
tf_aprilTagInBody: [1,0,0,0,
                    0,0,-1,0,
                    0,1,0,0,
                    0,0,0,1]
random_seed: 0
airsim:
    cam_name: 0
    wall_labels: []#[wall, pillar, surface]
    wall_color: [153, 108, 6]
    wall_seg_id: 1
    cube_label: Cube
    img_w: 1280
    img_h: 720
    dep_w: 1280
    dep_h: 720
    fov: 70
angular_scan_resolution:
    fine: 8
    coarse: 4
grid_mapping:
    grid_size: 1.0
    x_length: 6
    y_length: 6
    x_offset: -3
    y_offset: -3
    obstacle_thickness: 0.5
    free_dot_threshold: 0.4
    manual_align: False
    free_bearing_inflate: 5.0
    ocp_bearing_inflate: 1.0
imp_data_preprocess:
    overwrite_data: False
    save_feature_img: True
    save_feature_txt: True
    save_scan_txt: True
    nfeatures: 1000
    contrastThreshold: 0.1
    edgeThreshold: 5
marker_pose_samples:
    sampling_ratio: 1.0
    voxel_size: 0.05
    min_distance: 0.6
    outlier_distance: 3.0
similar_features:
    min_sim_score: 0.9
    min_distance: 2.0
    parallel_jobs: 1
    batch_size: 2000
    voxel_size: 0.05
marker_placement:
    marker_prior_std: [1.e-5, 1.e-5, 1.e-5, 1.e-5, 1.e-5, 1.e-5]
    marker_meas_std: [1.e-3, 1.e-3, 1.e-3, 1.e-3, 1.e-3, 1.e-3]
    cam_prior_std: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    lmk_prior_std: [5.e-2, 5.e-2, 5.e-2]
    pix_std: 1
    max_dist: 10
    max_angle: 45
    marker_num: 20
    most_vis_marker_percentages: [90] #[90]
    mean_max_weights: [0.5,0.5]
    pkl_res_path: None
    placed_marker_path: None
    ignore_features: False
evaluation_datasets:
    marker_nums: [0,5,10,15,20]
    imp_max_ratios: []
    rd_ids: [1] #[0,1,2,3,4]
    uc_ids: [0]
    size_ratios: [] #[25,50,75,125,150,175]
    tf_perturb: [] #[-25,-50,-75,-100,25,50,75,100]
    test_img_num: 100
    ref_res_pkl: /home/chad/datasets/ThreeDeeOffice/imp_res/90percent_markers/run0/res0.pkl
    test_cam_trans_noise_scale: 1.0
    test_cam_theta_noise_scale: 1.0
    test_sample_mean_weight_scales: [1] #[2,4,8,16] #[1]
    test_data_distributions: [unif] #[weighted,unif]
performance_evaluation:
    VLAD_visual_words: 10
    ball_tree_leaf_size: 10
    nearest_neighbor_imgs: 5
    parallel_jobs: 1
    trans_angle_max: [[0.01, 1],[0.05, 5],[0.1, 10],[0.2, 20],[0.3, 5],[0.3, 10],[0.3, 20],[0.3, 30],[0.5,50]]
    tag_loc_percent: [1.0]
    tag_family: tag36h11
    tag_size: 0.168
    dft_sift_params: True
    trans_tol: 1.0
    rad_tol: 1.0
baseline_method:
    unif_contour_min_distance: 0.6